-- 기존 테이블 삭제 (데이터가 있다면 백업 먼저!)
DROP TABLE ADMIN.PDFCOLLECTION;

-- 1024차원으로 재생성
CREATE TABLE ADMIN.PDFCOLLECTION (
    ID VARCHAR2(100 BYTE),
    TEXT CLOB,
    METADATA CLOB,
    EMBEDDING VECTOR(1024, *), -- 1024차원 벡터 for bge:m3:latest
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ADMIN.PDFCOLLECTION ADD PRIMARY KEY (ID)
USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255
TABLESPACE DATA ENABLE;

-- Vector 인덱스 생성 (HNSW 방식)
CREATE VECTOR INDEX ADMIN.VECTOR_IDX ON ADMIN.PDFCOLLECTION (EMBEDDING)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
WITH DISTANCE COSINE
WITH TARGET ACCURACY 95;
