# Custom Langflow Frontend with increased client_max_body_size
# Always uses the latest official langflow-frontend image as base
FROM langflowai/langflow-frontend:latest

# Modify the nginx template file to set client_max_body_size to 100MB
# The template is processed by entrypoint at container startup to generate /tmp/nginx/default.conf
USER root
RUN sed -i 's/${LANGFLOW_MAX_FILE_SIZE_UPLOAD}M/100m/g' /etc/nginx/conf.d/default.conf.template

# Switch back to nginx user
USER 101
